### ISSUE TITLE
Full code release schedule

### ISSUE THREAD

**Issue by IOYS-DEV** [sharinka0715/semantic-gaussians#1]
Thank you for the valuable research.
I am interested in conducting various experiments, 
but it seems that some parts of the code, such as the configuration files and dataloader.

Could you share the update schedule?

**Comment by sharinka0715** [comment]
Hi,

I think that the released code is able to reproduce the quantitative results reported in our paper. The configurations are in `configs/` and there is no special dataloader. You can refer to the [Usage](https://github.com/sharinka0715/semantic-gaussians?tab=readme-ov-file#usage) section to train 3D Gaussians, 2D projection, 3D semantic network, and evaluation on ScanNet dataset. As for qualitative results on MVImgNet and CMU Panoptic dataset, you can conduct 2D projection experiments by applying our default configs.

If you feel that some specific modules are missing, please describe them concretely. And we are planning to share our pre-trained 3D Gaussians and 3D semantic network soon, but we cannot promise an accurate schedule.
