### ISSUE TITLE
Question about distill.py

### ISSUE THREAD

**Issue by moqiyinlun** [sharinka0715/semantic-gaussians#11]
I run the distill.py after have the fusion result, in /data/new_disk4/shenzhh/semantic-gaussians/fusion/0.pt, but the code went wrong.

Traceback (most recent call last):
  File "/data/new_disk4/shenzhh/semantic-gaussians/distill.py", line 243, in <module>
    distill(config)
  File "/data/new_disk4/shenzhh/semantic-gaussians/distill.py", line 75, in distill
    dataset = FeatureDataset(
  File "/data/new_disk4/shenzhh/semantic-gaussians/dataset/feature_dataset.py", line 34, in __init__
    features = os.listdir(os.path.join(point_dir, scene))
FileNotFoundError: [Errno 2] No such file or directory: '/data/new_disk4/shenzhh/semantic-gaussians/fusion/cameras.json'

Since the edited config is given below:
scene:
  scene_path: "/data/new_disk4/scene20240201/data1/1150/image_undistortion_white"
  dataset_name: "cocomap"
  test_cameras: False
  colmap_images: "images"
  colmap_eval_hold: 8
  downscale_ratio: 1
  white_background: True
  device: "cuda:3"
  
pipeline:
  convert_shs_python: False
  compute_cov3d_python: False
  debug: False
  seed: 1

model:
  sh_degree: 3
  model_dir: "/data/new_disk4/scene20240201/data1/1150/output"
  dynamic: False
  load_iteration: 30000
  device: "cuda:3"

fusion:
  out_dir: "/data/new_disk4/shenzhh/semantic-gaussians/fusion"

distill:
  exp_name: openseg_new
  model_3d: MinkUNet34A
  voxel_size: 0.02
  aug: True
  feature_type: all
  lr: 0.001
  epochs: 100
  loss_type: cosine
  schedule_milestones: [20, 40, 60, 80, 100]
  schedule_gamma: 0.3
  batch_size: 1
  num_workers: 16
  test_interval: 10
  save_interval: 10

**Comment by sharinka0715** [comment]
Hi,

The 3D distillation experiments should be conducted on a scene dataset rather than a single scene. If you just want to try our semantic gaussians on a single scene, you do not need to conduct 3D distillation. You can just run `view_viser.py` to view performances on 2D projection results.
