### ISSUE TITLE
Questions about cofig for fusion.py

### ISSUE THREAD

**Issue by king1111sadjfoisja** [sharinka0715/semantic-gaussians#14]
Dear author:
I am having trouble understanding the config file for fusion.py:
![image](https://github.com/user-attachments/assets/e885f9b3-b714-4166-89a1-4e3ea322eba6)
In the figure,
I am not sure what `config.model.model_dir` and `config.fusion.depth` refer to,so i dont know the value of it
Hope you can elaborate me thanks a lot

**Comment by king1111sadjfoisja** [comment]
Additionally, I would like to know if installing MinkowskiEngine with pip affects the results, as you specifically noted in the readme.md to install it with Anaconda.
![image](https://github.com/user-attachments/assets/330fe1a1-c573-48da-a61d-a36e516db799)
I hope you can provide assistance, thank you!

**Comment by sharinka0715** [comment]
Hi,
`model.model_dir` refers to the 3D Gaussian Splatting model, which is obtained by train.py.
`fusion.depth` is a hyperparameter that used to control the depth generation method. You don't need to modify it.

**Comment by HuGhcat-code** [comment]
THANKS A lot,can i install MinkowskiEngine using pip?

**Comment by sharinka0715** [comment]
> THANKS A lot,can i install MinkowskiEngine using pip?

Of course you can install MinkowskiEngine in anyway you like. There is no difference between installation methods.
