### ISSUE TITLE
config.yaml file is missing from the step python fusion.py 

### ISSUE THREAD

**Issue by NagaPadma** [sharinka0715/semantic-gaussians#15]
![image](https://github.com/user-attachments/assets/c0e52525-4c61-4cc0-9a92-d106f59e9d05)

**Comment by king1111sadjfoisja** [comment]
same problem 
应在在fusion.py也要输出一下yaml文件

**Comment by sharinka0715** [comment]
Hi,
I did not get the problem. Could you please describe your problem more specifically? Thanks.

**Comment by NagaPadma** [comment]
> Hi, I did not get the problem. Could you please describe your problem more specifically? Thanks.

when i run python distill.py its looking for this yaml in fusion output folder.

PS: i have trained my model on Gaussian splatting original garden scene.

**Comment by sharinka0715** [comment]
> > Hi, I did not get the problem. Could you please describe your problem more specifically? Thanks.
> 
> when i run python distill.py its looking for this yaml in fusion output folder.
> 
> PS: i have trained my model on Gaussian splatting original garden scene.

Code in `distill.py` does not search for a `config.yaml`. The `config.yaml` in your code comes from the wrong parameters of `config.scene.scene_dir`. 

`distill.py` can never run on a single scene, instead, it runs on a large-scale dataset such as ScanNet. 

If you just want to try our semantic gaussians on a single scene, you do not need to conduct 3D distillation. You can just run `view_viser.py` to view performances on 2D projection results.

**Comment by Sugar55888** [comment]
@sharinka0715 Hi, so we need to run train.py and fusion.py for each scene in Scannet dataset. And then we can run distill.py to get the output 3D semantic network checkpoints. Is that right?

**Comment by sharinka0715** [comment]
> @sharinka0715 Hi, so we need to run train.py and fusion.py for each scene in Scannet dataset. And then we can run distill.py to get the output 3D semantic network checkpoints. Is that right?

@Sugar55888 Yes, that's right.

**Comment by Sugar55888** [comment]
@sharinka0715 Thank you!

**Comment by siwenwei** [comment]
> ![image](https://github.com/user-attachments/assets/c0e52525-4c61-4cc0-9a92-d106f59e9d05)

hi, have you solved this problem?
