### ISSUE TITLE
Visualizing part segmentation results

### ISSUE THREAD

**Issue by HuGhcat-code** [sharinka0715/semantic-gaussians#17]
Hi,
I rendered a mug scene from the MVImagnet dataset, and after running `view_viser.py`, I get the website shown below. 
However, when I input text prompts 'handle' and click 'apply text prompt,' nothing happens. 
How should I solve this issue?
![image](https://github.com/user-attachments/assets/5b20866b-7a25-4fe1-8a40-5ead265800b8)

PS:the part prompt "handle"is in the predefined classes as follows:
![image](https://github.com/user-attachments/assets/a98746b5-1bb8-49c6-941d-dd62b77c076b)

Any help is appreciated！

**Comment by sharinka0715** [comment]
Hi,
The default render mode is "RGB", so you can only view RGB Gaussians. If you want to view semantic results, you should click "Semantic" or "Relevancy" button at the top of the setting box.

**Comment by HuGhcat-code** [comment]
THANKS A LOT

**Comment by HuGhcat-code** [comment]
Dear author:
Unfortunately，the advice you gave me doesn't help:
After click "Semantic" or "Relevancy" button at the top of the setting box,I got absolutely nothing but a black background as follows:
![image](https://github.com/user-attachments/assets/cb20152a-866f-4904-9f68-a787932d5fa8)
Same condition happens when I click "Relevancy" button,however there are indeed results for RGB and Depth button：
![image](https://github.com/user-attachments/assets/8ed85ef3-3013-4c60-b5b1-345d48a2dedb)
I wanna know why I can get nothing more than a completely black background for the "Semantic" or "Relevancy" button,and how can I solve this!
Thanks a lot!
