### ISSUE TITLE
Following issue 17

### ISSUE THREAD

**Issue by HuGhcat-code** [sharinka0715/semantic-gaussians#18]
Dear author:
Unfortunately，the advice you gave me doesn't help:
After clicking "Semantic" or "Relevancy" button at the top of the setting box,I got absolutely nothing but a black background as follows:
![image](https://github.com/user-attachments/assets/59432070-f320-4309-b2da-0cd9fe394c9a)
Same situation happened when I click "Relevancy" button.
However there are indeed results for RGB and Depth button：
![image](https://github.com/user-attachments/assets/b82f3c66-1ef3-45da-a359-097c06ef9426)
I wanna know why I can get nothing more than a completely black background for the "Semantic" or "Relevancy" button,and how can I solve this!
Thanks a lot!

**Comment by sharinka0715** [comment]
It seems like you did not input the right prompt. You should input what class you want to seg at the top right "Text prompt" box, and click "Apply text prompt" button.

If you still cannot get proper results, I would like to suggest you to try OpenSeg or LSeg on larger scenes rather than MVImgNet, to get familiar with this Viser visualization interface.

**Comment by HuGhcat-code** [comment]
I noticed that some code in the fusion.py file is commented out; that should be the reason.
But I am still trying to resolve this issue.

**Comment by HuGhcat-code** [comment]
Could you please tell me how to realize the Part Segmentation Result in the paper?

**Comment by HuGhcat-code** [comment]
Could you please tell me how to realize the Part Segmentation Result in the paper?
![image](https://github.com/user-attachments/assets/f53a8e93-34bf-4862-a2d5-8940ef8b166f)

**Comment by sharinka0715** [comment]
> I noticed that some code in the fusion.py file is commented out; that should be the reason. But I am still trying to resolve this issue.

I don't think any commented code would affect the projection result. The commented code are for debug use, which can save semantic maps during fusion.

**Comment by sharinka0715** [comment]
> Could you please tell me how to realize the Part Segmentation Result in the paper? 

I have no idea about the reason why you cannot reproduce the result in our paper. Please make sure that:
1. Your 2D pretrained model is VLPart, and your target part is in [`predefined_classes`](https://github.com/sharinka0715/semantic-gaussians/blob/ae531372ee37e4016030362397ddb1c64ad4c58d/model/vlpart_predictor.py#L25).
2. You run `fusion.py` and get the 2D projection checkpoint `0.pt`, and you load it in `view_viser.py` by setting `render.fusion_dir` in `config.yaml`.
3. Input your target class and part (e.g.: `mug:handle`) in the `Text Prompt` box, and click `Apply Text Prompt`, then click `Relevancy` or `Semantic` to view semantic maps.

I would like to upload a part segmentation sample including a COLMAP scene, an RGB 3DGS, and a fusion checkpoint. You can try it with text prompt `guitar:fingerboard,guitar:bridge,guitar:hole,guitar:body,guitar:headstock`.

The download link is at https://drive.google.com/file/d/1EdmktauTcj5OgMqxoE81idKyqgaHESju/view?usp=drive_link

The result is as follows:
<img width="496" alt="1" src="https://github.com/user-attachments/assets/d08cda40-f5ba-41f6-a2e3-872fdf1d5604">
<img width="493" alt="2" src="https://github.com/user-attachments/assets/48a5b201-7f89-4c2f-9e39-bd4de64a413c">

Please carefully check your code and process.

**Comment by HuGhcat-code** [comment]
i know the reason:
At the end of the fusion.py script, there is a line that says:
`# model_2d.set_predefined_cls(SCANNET20_CLASS_LABELS)`
![image](https://github.com/user-attachments/assets/2f78994b-f948-4df5-b962-e16cce049865)
we should comment it out if we are not using SCANNET

**Comment by HuGhcat-code** [comment]
Dear author:
the download link you gave me has a 'scene' foder which contains the following:
![image](https://github.com/user-attachments/assets/d1451f28-ea24-454b-8bde-4641d7e6cc10)
I would like to know which folder you use as a scene to train 3DGS?
I simply used 'images' and 'sparse' folder to train 3DGS(neglecting the other 2 folders)
After training,i ran `fusion.py` and `view_viser.py` to get a result far worse than you provided as below:
(with the same prompt:`guitar:fingerboard,guitar:bridge,guitar:hole,guitar:body,guitar:headstock`)
![image](https://github.com/user-attachments/assets/f2f2f399-a3b7-4b5e-aaa8-05bdfeba01df)
![image](https://github.com/user-attachments/assets/9e5a3507-d37a-4caa-8b5c-c5371fd03881)
the image above is what i get retraining 3DGS,
below is simply running `view_viser.py` after configing(using fusion.pt and 3DGS model you provided)
I want to know the reason why big differences exit between those 2 pics and how can i refine the results of my own training?
Thanks a lot

**Comment by HuGhcat-code** [comment]
Furthermore,
I d like to know how you come up with the text prompt:
`guitar:fingerboard,guitar:bridge,guitar:hole,guitar:body,guitar:headstock`
seeing that all parts of guitar are not used in 'LVIS_PACO_VOCAB':
![image](https://github.com/user-attachments/assets/4771e51a-7c95-4b35-9200-c1787eacc4ba)

**Comment by sharinka0715** [comment]
Hi,
1. Training RGB Gaussians only needs `images` and `sparse` folders.
2. If you get worse results, you can try to save intermediate results that predicted by VLPart ([a probable code example](https://github.com/sharinka0715/semantic-gaussians/blob/ae531372ee37e4016030362397ddb1c64ad4c58d/fusion.py#L79-L104)). Semantic Gaussians can only project embeddings from pretrained models like VLPart, so if the foundation model cannot get the right result, we cannot get it either.
3. Not all parts are used is also because of the performance of VLPart. VLPart cannot tell all parts accurately. Besides, some parts overlaps (key and headstock, side and body, string and fingerboard), and some parts do not exist in the scene (pickguard, back).

**Comment by HuGhcat-code** [comment]
Thanks a lot!
However,I noticed that：For the same guitar scene, my 3DGS rendering results are much worse than yours,as shown in figures below:
![image](https://github.com/user-attachments/assets/11c7fbbe-e1a5-4f50-8c35-0714e589e863)
![image](https://github.com/user-attachments/assets/5161e188-6ae4-473b-aa74-849e05e33ff9)
I want to know why my rendering looks so blurry and which parts of the code I need to adjust to improve the results
I am currently using an NVIDIA RTX 3090 with single GPU training(cuda:0)
Thanks a lot

**Comment by HuGhcat-code** [comment]
I d like to add that:
the configuration i use in the webpage is maybe the same as yours:
(I am not entirely sure about the resolution scale you use,mine is just as the default)
![image](https://github.com/user-attachments/assets/2051ad13-3cf6-4a1b-ae1e-73fa0abc6d42)

**Comment by sharinka0715** [comment]
The blurry scene is related to the resolution scale. The default resolution is too low to render on fullscreen (approximately 480x640). You can change resolution scale to 4x. I render it on NVIDIA RTX 4090.

**Comment by HuGhcat-code** [comment]
Hi:
After clicking the '4x' button,the following interface is displayed:
![image](https://github.com/user-attachments/assets/2bfdd758-9894-46e0-a311-312c052134d1)
It seems that there is an issue with the connection?
It just keeps connecting and cannot connect,I dont know why
So I am having trouble getting the high-resolution rendering result

**Comment by HuGhcat-code** [comment]
Do you think it is due to the graphics card model?
I connect to a remote server via SSH（with NVIDIA RTX 3090）, but my local Windows system does not have a GPU.
I’m not sure if that’s the reason.

**Comment by sharinka0715** [comment]
I think it is not related to your client machine. The problem might be on your server.

Have you checked that the program on your server? The connection lost often results from the exception from the server.

If the server runs without exception but you cannot connect to the server, I will have no idea towards that.
