### ISSUE TITLE
Difference between rendering results and intermediate results

### ISSUE THREAD

**Issue by HuGhcat-code** [sharinka0715/semantic-gaussians#19]
Dear author:
Thank you for open-source such a great work!
When i was fusing the guitar scene you gave me(running `fusion.py`),I saved the intermediate semantic maps as shown below(one of many):
![image](https://github.com/user-attachments/assets/16300841-61e0-45ec-89d0-99bc25297188)
The other maps are basicly alike.
After fusion,I ran `view_viser.py`,**only to see a different semantic rendering result**!
![image](https://github.com/user-attachments/assets/123678ab-0938-4063-a96a-7cb4e21b290e)
**Some parts that are clearly not segmented in the intermediate semantic map are shown in the final result**
I want to know why
Appreciate your help

**Comment by sharinka0715** [comment]
Hi,
I don't think it is possible that classes which are not segmented by VLPart can be shown in the final result. However, classes that are distinguished by VLPart is not necessarily to be in the intermediate segment map. 

You should refer to the [code of semantic map generation from VLPart](https://github.com/sharinka0715/semantic-gaussians/blob/ae531372ee37e4016030362397ddb1c64ad4c58d/model/vlpart_predictor.py#L80-L124). All parts segmented by VLPart could **overlap**, and the CLIP embeddings of these overlapped areas are **averaged**.

If you want to see the raw output of VLPart, please try to show the masks and instances from [here](https://github.com/sharinka0715/semantic-gaussians/blob/ae531372ee37e4016030362397ddb1c64ad4c58d/model/vlpart_predictor.py#L74) and [here](https://github.com/sharinka0715/semantic-gaussians/blob/ae531372ee37e4016030362397ddb1c64ad4c58d/model/vlpart_predictor.py#L116).
