### ISSUE TITLE
About CUDA version

### ISSUE THREAD

**Issue by king1111sadjfoisja** [sharinka0715/semantic-gaussians#2]
Dear Author:
I would like to know whether this project has strict restrictions on CUDA versions 11.8；Personally I am using CUDA 11.6 but I don't know if that can meet the requirement
Should I reinstall CUDA11.8?
Any help is greatly appreciated!

**Comment by sharinka0715** [comment]
Hi,
Our repository does not have strict restrictions on CUDA versions, but we have only tested our code on CUDA 11.8. I don't think there are problems for CUDA 11.x.

**Comment by king1111sadjfoisja** [comment]
Thanks a lot!
