### ISSUE TITLE
Changing 2D segmentation model

### ISSUE THREAD

**Issue by HuGhcat-code** [sharinka0715/semantic-gaussians#20]
Hi!
Dear author:
Thank you for open-source such a great work!
Due to the need of my current research，I would like to make a change based on your work , which would require another specific 2D segmentation model that is **not mentioned in the paper**.
I wonder if it is possible to replace the 2D segmentation model with something else that is **not mentioned in the paper**.
What are the **requirements** for such a 2D segmentation model，and what **parts of the code** should I change to complete the replacement.
Any tips you can give me would be greatly appreciated!!!
Sincerely hope that you can offer me some clue!!!
Thanks a lot!!!

**Comment by sharinka0715** [comment]
Hello,

If you want to add a new segmentation model which is not used in our paper, you should implement a `Predictor` just as [openseg_predictor.py](https://github.com/sharinka0715/semantic-gaussians/blob/main/model/openseg_predictor.py). 

You need to implement two methods, `extract_image_feature(img_dir)` which receives a image directory as input and outputs a pixel-wise segmentation embedding map, and `extract_text_feature(labelset)` which receives a list of strings as input and outputs the corresponding text embeddings.

I don't think it is a hard problem, as there are few requirements between segmentation models and the Semantic Gaussians code.

**Comment by HuGhcat-code** [comment]
Thanks a lot!
Should I make sure that **the vocabulary of the segmentation results**(from my own 2D segmentation model) included in the CLIP model?

**Comment by HuGhcat-code** [comment]
Thanks a lot!
Should I make sure that the vocabulary of the segmentation results(from my own 2D segmentation model) included in the CLIP model?
Otherwise maybe the text embeddings cannot match the segmentation results well?

**Comment by HuGhcat-code** [comment]
Thanks a lot!
Should I make sure that **the vocabulary of the segmentation results**(from my own 2D segmentation model) included in the CLIP model?
Otherwise maybe the text embeddings cannot match the segmentation results well?

**Comment by sharinka0715** [comment]
> Thanks a lot! Should I make sure that **the vocabulary of the segmentation results**(from my own 2D segmentation model) included in the CLIP model? Otherwise maybe the text embeddings cannot match the segmentation results well?

@HuGhcat-code Of course you should.

**Comment by HuGhcat-code** [comment]
Dear author:
I encountered an issue while completing the `extract_image_feature(img_dir)` method:
I noticed that the return value of this method should be **a pixel-wise segmentation embedding map**,however,I can only get **a per-pixel class index map**.（That is,a single-channel image with the same size as the input image, where each pixel value is **an integer** (0-11)，11 is the number of categories I need to classify.）
Could you please tell me how to convert **the class index map** I obtained into the **segmentation embedding map** required by this method?
Thanks a lot!

**Comment by sharinka0715** [comment]
> Dear author: I encountered an issue while completing the `extract_image_feature(img_dir)` method: I noticed that the return value of this method should be **a pixel-wise segmentation embedding map**,however,I can only get **a per-pixel class index map**.（That is,a single-channel image with the same size as the input image, where each pixel value is **an integer** (0-11)，11 is the number of categories I need to classify.） Could you please tell me how to convert **the class index map** I obtained into the **segmentation embedding map** required by this method? Thanks a lot!

@HuGhcat-code 

No, you cannot get a embedding map from a index map. It seems that the classes are closed-set and you have specific numbers of classes in your setting. However, our Semantic Gaussians are designed as an open-vocabulary scene understanding method, so we process the scene by CLIP embeddings.

If you really want to use our method as a closed-set method, you can try some tricky approaches, e.g., transfer your class indexes to one-hot embeddings, or encode your class names by a CLIP text encoder.
