### ISSUE TITLE
Which scenes did you use for evaluation?

### ISSUE THREAD

**Issue by Kim-GeonU** [sharinka0715/semantic-gaussians#23]
Hi, thank you for open-sourcing your code for the community.

I have a question about 12 scenes in validation set, which are used for evaluation.

Can you open the sequence numbers of the scenes used for evaluation? 

Thank you.

**Comment by sharinka0715** [comment]
Hello,
The 12 scenes in scannet validation set are: `scene0050_02`, `scene0144_01`, `scene0221_01`, `scene0300_01`, `scene0354_00`, `scene0389_00`, `scene0423_02`, `scene0427_00`, `scene0494_00`, `scene0616_00`, `scene0645_02`, and `scene0693_00`. You can found them at [the supplementary material of this paper](https://openaccess.thecvf.com/content/CVPR2023/supplemental/Siddiqui_Panoptic_Lifting_for_CVPR_2023_supplemental.pdf).

We introduce in the "Experimental Setup" section that we use the same 12 scenes from reference `[45] Panoptic lifting for 3d scene understanding with neural fields`. The 12 scenes are widely used in closed-set panoptic segmentation methods which out method can compare with.

**Comment by Kim-GeonU** [comment]
Thank you so much for your real quick reply!!
