### ISSUE TITLE
Inquiry about training time in RTX 4090

### ISSUE THREAD

**Issue by gtziafas** [sharinka0715/semantic-gaussians#24]
Hey there, thanks for the project! May I ask how much time did it take to train e.g. in the 4 LERF scenes in your RTX-4090? I mean for training the GS + distilling the 3D semantic network?

**Comment by sharinka0715** [comment]
Hello,
We train 10,000 steps for 3D Gaussians in each scene, and train 100 epochs for 3D distillation. I did not record the specific training time on our device, but it would not take a long time. 
If you find your training process is slow, or you meet CUDA OOM in distillation, you should reduce the input size of training image. The original resolutions of LERF and Mip-NeRF 360 dataset are too high for our work.
