### ISSUE TITLE
question about the fusion yaml file‘ parameters

### ISSUE THREAD

**Issue by ferryman123** [sharinka0715/semantic-gaussians#25]
hi,I want to know the meaning of the parameter [img_dim]. Is it the size of the rendered image or the size of the real image, do I need to change it if the size of the image is different for each dataset？

fusion:
  img_dim: **[648, 484]**
  num_workers: 8
  model_2d: openseg # choose from openseg, lseg, samclip, vlpart
  depth: render # choose from image, render, surface, none
  depth_scale: 1000.0
  visibility_threshold: 0.05
  cut_boundary: 10
  n_split_points: 999999999 # train: 80000, eval: 999999999 (large enough)
  num_rand_file_per_scene: 1 # train: 5, eval: 1

**Comment by sharinka0715** [comment]
Hello,
During 2D fusion, the images in dataset will be resized to this dimension and be segmented. The value `[648, 484]` is for ScanNet dataset. You need to change it to a proper value if the size of image is different from ScanNet.
