### ISSUE TITLE
Does it support a pre-trained 3D Gaussian Splat?

### ISSUE THREAD

**Issue by abrahamezzeddine** [sharinka0715/semantic-gaussians#6]
Hello,

I am wondering if this will support a pre-trained 3DGS from Nerfstudio for example and just append the masks/segmentation into the .ply file?

**Comment by sharinka0715** [comment]
Hi,
The format of our 3DGS follows the [official repository of 3DGS](https://github.com/graphdeco-inria/gaussian-splatting). If you have .ply file trained from this repository, you can directly use them in our repo. I am not sure what format Nerfstudio uses.

**Comment by abrahamezzeddine** [comment]
@sharinka0715 

They have the same file format, same attributes in the header. However, it might be that the data is normalized because normalised data works better on tensors CUDA. But that I can fix. 

Could you please explain how I could (if we assume the trained splat PLY is in the same format, can append the semantics into the ply file)? 

Nerfstudio provides a good and clean splats compared to the official implementation.

**Comment by sharinka0715** [comment]
@abrahamezzeddine 

I think you can directly load the `.ply` file of official 3DGS format in [fusion.py](https://github.com/sharinka0715/semantic-gaussians/blob/main/fusion.py#L36). 

`fusion.py`, which performs 2D versatile projection, receives the normal 3DGS as input, and it will create semantic features to create Semantic Gaussians. You can set the colmap folder (with `images/`, `sparse/`) in [scene.scene_path](https://github.com/sharinka0715/semantic-gaussians/blob/main/config/fusion_scannet.yaml#L2), and set the `.ply` file in [model.model_dir](https://github.com/sharinka0715/semantic-gaussians/blob/main/config/fusion_scannet.yaml#L19).
