### ISSUE TITLE
Distill progress OOM

### ISSUE THREAD

**Issue by ChenLu-china** [sharinka0715/semantic-gaussians#7]
Dataset: room of Mipnerf360
Device: 24G double 4090
![20240702-110313](https://github.com/sharinka0715/semantic-gaussians/assets/74493433/b49465e4-b353-439a-913e-81261eb24676)

**Comment by ChenLu-china** [comment]
I noticed that you also used RTX 4090 without the OOM problem mentioned. So what should I change the parameters to avoid this?

**Comment by sharinka0715** [comment]
@ChenLu-china 

Hi,

We did not perform distill experiments on Mip-NeRF 360, as there are less than 10 scenes in this dataset thus hard to distill. Instead, we conduct our scene editing experiments by using our 2D versatile projection results.

If you want to distill Mip-NeRF 360 scenes, you might train a 3DGS with fewer Gaussian points (which means low fidelity). RTX 4090 can only distill ScanNet scenes 1 scene per batch, and it will face OOM error when producing larger scenes.

**Comment by ChenLu-china** [comment]
@sharinka0715 

Thanks for your reply, 
I will try scannet later~
