### ISSUE TITLE
Request for Access to MipNeRF Dataset for Reproducing Semantic Gaussians Results

### ISSUE THREAD

**Issue by NagaPadma** [sharinka0715/semantic-gaussians#9]
Hi,

I am currently working on reproducing the results from the "Semantic Gaussians: Open-Vocabulary Scene Understanding with 3D Gaussian Splatting" paper. However, I am having difficulty downloading the MipNeRF dataset.

Could you please provide access to the MipNeRF dataset by keeping it in a folder for download? This would greatly help in my efforts to replicate the results and further my research.

**Comment by sharinka0715** [comment]
Hi,

Sorry for hear that, but I don't think I have permissions to redistribute the MipNeRF dataset. The dataset is stored on the google storage, so you should not have difficulty downloading it if you can visit Google. You may try other datasets to replicate our results, as we did not emphasize the MipNeRF dataset in our paper.

**Comment by NagaPadma** [comment]
Please recommend me which dataset to use to reproudce the results. and where to download it from?
I would prefer colmap dataset but i am open to work with anyother format as well.

**Comment by sharinka0715** [comment]
> Please recommend me which dataset to use to reproudce the results. and where to download it from? I would prefer colmap dataset but i am open to work with anyother format as well.

All datasets that used in our paper is listed in the README.md. We recommend ScanNet dataset, though it is not in COLMAP format.
